language: node_js

cache: yarn

node_js:
    - 'lts/*'
    - 'node'

os:
    - windows
    - linux
    - osx

# See https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
    - YARN_GPG=no

# safelist
branches:
    only:
        - master
        - /^feat/.*$/
        - /^v\d*\.\d*\.\d*$/
        - /^dependabot/.*$/

script: echo "Running tests against $(node -v)..."

jobs:
    allow_failures:
        - os: windows
        - os: osx
    include:
        - stage: Produce Coverage
          node_js: node
          script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
        - stage: Check for Code Duplication
          node_js: node
          script: yarn dupe-check
        - stage: NPM release
          deploy:
            provider: npm
            email: devfrazs@outlook.com
            api_key:
                secure: Rb7NRsAUUWQz8dOd7YXpbHusN+dy7zu/lpr7QcGeGG2rd8oXq78sV3J06ojkA8hcIOghCReqKv1Z4nnaj3wV1shb64+BjcVOwQyELta14Cm33HI3VaiBwRI4oeZVy1fRrEJgGnyhxGwmBtmsjQn/oxm1ivIbaDOm2AT3r3nRUp3S+4WmN+fDmsA9kF+BwZWgIsbUr6akJLI7HCZg04WBurxIjbeKyVmTub27TKM+/0gDOIAvkRyCXAT0JXDSNMUdKfhcEWe+7jaE1qvD55V1wL9HMtEAEvI11tvnXLgTwMc0M5tpCdUXLN6aK9PYTMtQG0M0kKBdfrommXLJrcPGgsXsQNs8a3W9+8KBGHaMDivKdZ9+6ztCcNmDpZ3ZBnf7CXiWTR+YxLr2iz8owJtaaSFgh42plARkiG+gxOmwbAD3hy0cXZUFyrnTrZcRWG9ph8bhUM70In0DR6KfKCJEVQ8smwvgkbVqkxIa7Do5XdR8droV9jZnZtzSApwB+lt2RDgKnXA3PbaRQpxzCLrEc2EzDJfP/J/LZxMvcA2wy9a/Fz7Q9JFoyGUG1laoq/Jb1bLj9REYvClWR6U6rtpr4OkV0iSY40oPf4acKlkCalJDpc3NVMn1vCzO6/v7bxxDVjGEQEBPariU2JcFBgaT5R43LaRCAxPFi/kt054yFaI=
            on:
                tags: true